medications_data = {
    'enrofloxacin (baytril)': "Enrofloxacin, known by the brand name Baytril, is a broad-spectrum antibiotic commonly used in veterinary medicine. It is effective against a wide range of bacterial infections in animals, including respiratory, urinary tract, and skin infections. Baytril comes in various forms such as tablets, injectable solutions, and oral suspensions. Look for the Baytril label to ensure you are getting the right medication for treating bacterial infections in your pets.",
    'ceftazidime (fortaz)': "Ceftazidime, marketed under the brand name Fortaz, is a potent antibiotic belonging to the cephalosporin class. It is primarily used to treat serious bacterial infections, including respiratory tract infections, urinary tract infections, skin infections, and infections in the abdomen. Fortaz is available in injectable forms and is administered under veterinary supervision to ensure proper dosing and effectiveness against targeted bacterial strains.",
    "doxycycline": "Doxycycline is an antibiotic used to treat bacterial infections such as those caused by canine distemper and psittacosis. It works by inhibiting bacterial protein synthesis, effective against a wide range of bacterial infections.",
    "amoxicillin": "Amoxicillin is a broad-spectrum antibiotic that inhibits bacterial cell wall synthesis, used to treat secondary bacterial infections associated with canine distemper.",
    "rabies vaccine": "The rabies vaccine is administered as part of post-exposure prophylaxis (PEP) to prevent the onset of rabies following exposure to the virus. It stimulates the body's immune system to produce antibodies against the rabies virus.",
    "rabies immunoglobulin": "Rabies immunoglobulin provides immediate passive immunity by supplying ready-made antibodies against the rabies virus, used in conjunction with the rabies vaccine in PEP.",
    "phenobarbital": "Phenobarbital is an anticonvulsant medication used to control seizures in dogs affected by canine distemper. It stabilizes electrical activity in the brain to prevent seizures.",
    "potassium bromide": "Potassium bromide is an anticonvulsant used in dogs to control seizures associated with canine distemper. It is often used in combination with other anticonvulsants like phenobarbital.",
    "atropine": "Atropine is an anticholinergic medication used to reduce excessive salivation in mammals by inhibiting the action of acetylcholine on muscarinic receptors.",
    "glycopyrrolate": "Glycopyrrolate is an anticholinergic agent used to decrease excessive salivation in mammals by reducing the secretions of the salivary glands.",
    "pseudoephedrine": "Pseudoephedrine is a decongestant used to relieve nasal discharge in animals by reducing swelling and congestion in the nasal passages.",
    "tobramycin eye drops": "Tobramycin eye drops are an antibiotic treatment for eye discharge caused by bacterial infections in mammals, aves, and reptiles.",
    "ciprofloxacin eye drops": "Ciprofloxacin eye drops are an antibiotic used to treat bacterial eye infections causing eye discharge in mammals, aves, and reptiles.",
    "artificial tears": "Artificial tears are lubricating eye drops used to relieve dryness and irritation in the eyes, often used as supportive care for animals with eye discharge."
}