"""initial migration

Revision ID: 467eb52f9359
Revises: 
Create Date: 2026-03-16 20:02:04.540093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467eb52f9359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illnessesremedies')
    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remedy', sa.String(), nullable=True))

    with op.batch_alter_table('illnessesclassifications', schema=None) as batch_op:
        batch_op.alter_column('illness_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('classification_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('illnessessymptoms', schema=None) as batch_op:
        batch_op.alter_column('illness_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('symptom_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('illnessessymptoms', schema=None) as batch_op:
        batch_op.alter_column('symptom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('illness_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('illnessesclassifications', schema=None) as batch_op:
        batch_op.alter_column('classification_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('illness_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('illnesses', schema=None) as batch_op:
        batch_op.drop_column('remedy')

    op.create_table('illnessesremedies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('illness_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remedy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['illness_id'], ['illnesses.id'], name='fk_illnessesremedies_illness_id_illnesses'),
    sa.PrimaryKeyConstraint('id', name='illnessesremedies_pkey')
    )
    # ### end Alembic commands ###
